---
# Location where configuration files will be stored.
config_dir: '~/internet-pi'

# IPv6 configuration: You can specify your desired subnet for docker-compose here.
docker_ipv6_enable: true   # if you change this variable, you must tear down containers first so the network is created from scratch
docker_ipv6_subnet: 2001:3984:3989::/64
docker_ipv6_gateway: 2001:3984:3989::1

# Domain names configuration (related services need to be enabled).
domain_name_enable: false

# Pi-hole configuration.
pihole_enable: false
pihole_hostname: pihole
pihole_timezone: Europe/Berlin
pihole_port_http: 8080
pihole_port_https: 44443

# Raspberry monitoring configuration
raspberry_monitoring_enable: true
telegraf_retention_policy: '90d'
telegraf_password: 'admin'

# Internet monitoring configuration.
monitoring_enable: true
monitoring_speedtest_interval: 60m
monitoring_ping_interval: 5s
monitoring_ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - https://www.google.com/;google.com
  - https://github.com/;github.com
  - https://soongjr.mooo.com/;soongjr.mooo.com

# Shelly Plug configuration. (Also requires `monitoring_enable`)
shelly_plugs_enable: true
shelly_plugs:           # list of Shelly Plugs to connect to
  - name: Fridge
    hostname: "shellyplug-fridge"
    port: 9924
  - name: Printer
    hostname: "shellyplug-printer"
    port: 9925

# AirGradient configuration. (Also requires `monitoring_enable`)
airgradient_enable: false

# Starlink configuration. (Also requires `monitoring_enable`)
starlink_enable: false

# Temperature Probe configuration. (Also requires `monitoring_enable`)
temp_probes_enable: true
# probes directly connected to the host
temp_probes:
  - name: "Inside"         # human-readable name you wish to give this probe
    id: "28-06201cd5251b"  # ID of the probe (check which folder in /sys/devices has a file named w1_slave)
    master: "w1_bus_master1" # master device this probe is assigned to
    # GPIO pin the data signal of the probe is connected to (will be set up for one-wire communication):
    # Changing or enabling this setting will require a reboot of the pi.
    pin: 4
    port: 9920             # port for prometheus to reach the exporter
  - name: "Outside"        # human-readable name you wish to give this probe
    id: "28-1f68841e64ff"  # ID of the probe (check which folder in /sys/devices has a file named w1_slave)
    master: "w1_bus_master2" # master device this probe is assigned to
    # GPIO pin the data signal of the probe is connected to (will be set up for one-wire communication):
    # Changing or enabling this setting will require a reboot of the pi.
    pin: 17
    port: 9921             # port for prometheus to reach the exporter
# probes exposed elsewhere in the network
temp_probes_ext:
  - name: "pi-pico"        # human-readable name you wish to give this probe in grafana
    hostname: "pi-pico"    # where to reach the client
    port: 80               # port for prometheus to reach the client
