---
# By default, applications containers get installed once and not updated automatically by later ansible runs.
# To tell chocolatey to upgrade applications, set this to "true".
# You might not want to randomly update apps while rolling out a change to your config
# and instead deliberately do so with a dedicated run without any other change.
# So this should normally be set to false and only changed for a single run when you're ready to update.
chocolatey_update_apps: false

# Install Steam:
steam_enable: false

# Install nextcloud:
nextcloud_enable: true

# Install keepass:
keepass_enable: false

# Install VS Code:
vscode_enable: true

# Set up WSL (Windows Terminal and Docker Desktop both benefits from this):
wsl_enable: false
wsl_distribution: Debian  # distribution to use/install, only Debian is tested!
wsl_distribution_makedefault: false  # make this distribution the default
wsl_user: soongjr
# wsl_password:  # must be specified in secrets.yml!

# Install Windows Terminal:
terminal_enable: true

# Install Docker Desktop:
docker_desktop_enable: false
