---
# By default, applications containers get installed once and not updated automatically by later ansible runs.
# To tell chocolatey to upgrade applications, set this to "true".
# You might not want to randomly update apps while rolling out a change to your config
# and instead deliberately do so with a dedicated run without any other change.
# So this should normally be set to false and only changed for a single run when you're ready to update.
chocolatey_update_apps: false

# Install Steam:
steam_enable: false

# Install nextcloud:
nextcloud_enable: false

# Install keepass:
keepass_enable: false

# Install VS Code:
vscode_enable: true
