---
# By default, applications containers get installed once and not updated automatically by later ansible runs.
# To tell chocolatey to upgrade applications, set this to "true".
# You might not want to randomly update apps while rolling out a change to your config
# and instead deliberately do so with a dedicated run without any other change.
# So this should normally be set to false and only changed for a single run when you're ready to update.
chocolatey_update_apps: false

# Install Steam:
steam_enable: false

# Install nextcloud:
nextcloud_enable: false
# nextcloud_url: "<URL>"  # optional, will only install and not configure if this is missing
# nextcloud_local_path: "<path>"
# todo: nextcloud_user and nextcloud_password in secrets.yml

# Install keepass:
keepass_enable: false
# keepass_database_path: "<path>"  # optional, will only install and not configure if this is missing
# Note: keepass_database_path has to exist before running the playbook
# (unless it's on nextcloud and we implement waiting for a sync...)
# todo: keepass_password in secrets.yml
