---
- name: Windows Client config
  hosts: windows_client
  # become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - example.config.yml
        - config.yml

  tasks:
    - name: Execute basic tasks.
      ansible.builtin.import_tasks: tasks/basic.yml

    - name: Setup Steam.
      ansible.builtin.import_tasks: tasks/steam.yml
      when: steam_enable
