---
- name: Windows Client config
  hosts: windows_client
  gather_timeout: 600  # longer timeout accounting for delayed startup of WinRM service
  become_method: ansible.builtin.runas

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - example.config.yml
        - config.yml
    - name: Load secrets.
      ansible.builtin.include_vars: "{{ item }}"
      when: item is file
      loop:
        - secrets.yml
  tasks:
    - name: Execute basic tasks.
      ansible.builtin.import_tasks: tasks/basic.yml

    - name: Setup Steam.
      ansible.builtin.import_tasks: tasks/steam.yml
      when: steam_enable

    - name: Setup Nextcloud.
      ansible.builtin.import_tasks: tasks/nextcloud.yml
      when: nextcloud_enable

    - name: Setup KeePass.
      ansible.builtin.import_tasks: tasks/keepass.yml
      when: keepass_enable

    - name: Setup Visual Studio Code.
      ansible.builtin.import_tasks: tasks/vscode.yml
      when: vscode_enable

    - name: Setup WSL.
      ansible.builtin.import_tasks: tasks/wsl.yml
      when: wsl_enable

    - name: Setup Windows Terminal.
      ansible.builtin.import_tasks: tasks/terminal.yml
      when: terminal_enable

    - name: Setup Docker Desktop.
      ansible.builtin.import_tasks: tasks/docker-desktop.yml
      when: docker_desktop_enable
