---
- name: Windows Client config
  hosts: windows_client
  gather_timeout: 600  # longer timeout accounting for delayed startup of WinRM service
  become_method: ansible.builtin.runas

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - example.config.yml
        - config.yml
    - name: Load secrets.
      ansible.builtin.include_vars: "{{ item }}"
      when: item is file
      loop:
        - secrets.yml
  tasks:
    - name: Execute basic tasks.
      ansible.builtin.import_tasks: tasks/basic.yml

    - name: Setup Steam.
      ansible.builtin.import_tasks: tasks/steam.yml
      when: steam_enable

    - name: Setup Nextcloud.
      ansible.builtin.import_tasks: tasks/nextcloud.yml
      when: nextcloud_enable

    - name: Setup KeePass.
      ansible.builtin.import_tasks: tasks/keepass.yml
      when: keepass_enable

    - name: Setup Visual Studio Code.
      ansible.builtin.import_tasks: tasks/vscode.yml
      when: vscode_enable

    - name: Setup WSL.
      ansible.builtin.import_tasks: tasks/wsl.yml
      when: wsl_enable

    - name: Setup Windows Terminal.
      ansible.builtin.import_tasks: tasks/terminal.yml
      when: terminal_enable

    - name: Setup Docker Desktop.
      ansible.builtin.import_tasks: tasks/docker-desktop.yml
      when: docker_desktop_enable

# TODOs:
# remove keepass setup from ansible, start `"<nextcloud_root>\Programs\Keepass\KeePass.exe"` instead (if exists, requires re-run of playbook after user has logged into nextcloud and finished sync...)
# Firefox/Chrome (`choco install -e "Firefox"`/`"GoogleChrome"`) and restore bookmarks from json file, install extensions, disable password manager...
# For Windows "N" editions: enable Windows MediaFeaturePack: https://support.microsoft.com/en-us/topic/media-feature-pack-list-for-windows-n-editions-c1c6fffa-d052-8338-7a79-a4bb980a700a
# Adobe Acrobat PDF reader
# Office
# Solid Edge
# WISO Mein Geld + Datenwiederherstellung
# Beyond Compare 4
# CrystalDiskInfo and CrystalDiskMark
# DBBrowser
# Greenshot
# ImageMagick
# Inkscape
# MPC-HC: `choco install -e "mpc-hc-clsid2"`
# OpenSCAD
# Ultimaker Cura
# USBIPD-WIN project (no choco, use `winget install --interactive --exact dorssel.usbipd-win --accept-source-agreements --accept-package-agreements`)
#    Note that using winget is not supported vias WinRM or ssh... https://github.com/microsoft/winget-cli/issues/256
#    And "--interactive" is needed to prevent restart, but then opens a GUI wizards (ansible has a "may-restart" property I think...)
#    And there's no chosolatey package for 
# apply registry patches:
#  - context menu entries for "add to MPC-HC playlist" and "recode video"
# after everything is done, disable WinRM (and/or remove this machine as a trusted host)
