---
- name: Ensure WinRM starts when the system has settled and is ready to work reliably
  # this is important for rebooting during ansible run
  ansible.windows.win_service:
    name: WinRM
    start_mode: delayed

- name: Ensure Chocolatey itself is installed, using community repo for the bootstrap
  chocolatey.chocolatey.win_chocolatey:
    name: chocolatey

- name: Install git
  chocolatey.chocolatey.win_chocolatey:
    name: git
    state: present

- name: Upgrade installed packages
  chocolatey.chocolatey.win_chocolatey:
    name: all
    state: latest
  when: chocolatey_update_apps
