---
- name: Ensure Chocolatey itself is installed, using community repo for the bootstrap
  chocolatey.chocolatey.win_chocolatey:
    name: chocolatey

- name: Install git
  chocolatey.chocolatey.win_chocolatey:
    name: git
    state: present

- name: Upgrade installed packages
  chocolatey.chocolatey.win_chocolatey:
    name: all
    state: latest
  when: chocolatey_update_apps
