---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
      - win/main
  schedule:
    - cron: "3 2 * * 0"

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install test dependencies.
        run: pip3 install -r requirements.txt && ansible --version

      - name: Lint yaml
        run: yamllint .
      - name: Lint ansible
        run: ansible-lint
